---
    name: Test
    # This Workflow was written by CSykes
    on:
      workflow_dispatch:
      # pull_request:
        # types:
          # - closed
        # paths:
          # - "src/manifest.yml"
          # - ".github/workflows/*.yml"

    jobs:
      BuildAndTest:
        strategy:
          matrix:
            os: [ 'windows-latest' ]
        runs-on: ${{ matrix.os }}
        
        steps:
              
          - uses: actions/checkout@v3
    
          - name: Install dependencies
            run: dotnet restore
    
          - name: Build
            run: dotnet build --configuration Release --no-restore

          - id: yak
            uses: crashcloud/yak-publish@main
            with:
              package-name: 'NUnitTestRunner'
              token: ${{ secrets.YAK_TOKEN }}
              build-path: 'src/bin/**/**/net48/'
              publish: 'production'
              platform: ${{ matrix.os }}
